version: '3'
services:
  web:
    user: node

    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_COMPOSE_VERSION: 1.25.4

    environment:
      PORT: 3000
      POSTGRES_HOST: db
      DB_PORT: 5432
      DB_TYPE: postgres
      DB_NAME: people
      POSTGRES_USER: calexslash
      POSTGRES_PWD: password

    volumes:
      - vscode-server-extensions:/home/node/.vscode-server/extensions
      - vscode-server-insiders-extensions:/home/node/.vscode-server-insiders/extensions
      - bash-history:/commandhistory
      - node-modules:/workspace/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace:cached

    command: sleep infinity

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: calexslash
      POSTGRES_PASSWORD: password
      POSTGRES_DB: people
    ports:
      - "4321:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./files/pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

  nginx:
    image: nginx:alpine
    volumes:
      - ./files/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 127.0.0.1:23001:80

volumes:
  global-node-modules:
  node-modules:
  bash-history:
  vscode-server-extensions:
  vscode-server-insiders-extensions:
  pgdata:
  pgadmin:
